apiVersion: v1
data:
  secretkey: RFdCdEI3Wlkwd2d2azJ4MTBZMTFNdGdVOU9KejVDTE0ycHhvT1U4bTU5bGU3QUE5Uit3UDRQVmx2RUZaTzQ4dlFZYzBXdmJVZlNUMkRtTHpVbHZsaFprWkEzT2xVNlRnSjIzdnpycDl5YzA2bXFLRGZJcXRNVEhPYWlEVEJGek5OUXN3Z2RUb0dlY1U0dHNDQTdYT2tYd2VvTjNBUkZTZTdkMmxKakJteGxRPQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
